### ISSUE TITLE
animdl 1.7.15 regression test failure

### ISSUE THREAD

**Issue by chenrui333** [justfoolingaround/animdl#274]
👋 trying to build the latest release, but run into some build issue. The error log is as below:

<details>
<summary>error build log</summary>

```
  │ /opt/homebrew/Cellar/animdl/1.7.15/libexec/lib/python3.11/site-packages/anim │
  │ dl/__main__.py:80 in __animdl_cli__                                          │
  │                                                                              │
  │    77 │   │   │   │   client.get(                                            │
  │    78 │   │   │   │   │   f"https://raw.githubusercontent.com/{author}/{repo │
  │    79 │   │   │   │   ).text,                                                │
  │ ❱  80 │   │   │   ).group(1)                                                 │
  │    81 │   │   │                                                              │
  │    82 │   │   │   tuplisied_upstream, tuplised_current_version = tuple(      │
  │    83 │   │   │   │   map(int, upstream_version.split("."))                  │
  │                                                                              │
  │ ╭───────────────────────────────── locals ─────────────────────────────────╮ │
  │ │          author = 'justfoolingaround'                                    │ │
  │ │          branch = 'master'                                               │ │
  │ │          client = <httpx.Client object at 0x103e2a[85](https://github.com/Homebrew/homebrew-core/actions/runs/5255516838/jobs/9495700189#step:3:86)0>                   │ │
  │ │         console = <console width=80 None>                                │ │
  │ │       constants = <module 'animdl.core.cli.helpers.constants' from       │ │
  │ │                   '/opt/homebrew/Cellar/animdl/1.7.15/libexec/lib/pytho… │ │
  │ │             ctx = <click.core.Context object at 0x1041915[90](https://github.com/Homebrew/homebrew-core/actions/runs/5255516838/jobs/9495700189#step:3:91)>             │ │
  │ │  disable_update = False                                                  │ │
  │ │        greeting = 'It is 08:53 AM on a [bold red]beautiful[/] Tuesday!'  │ │
  │ │        regexlib = <module 'regex' from                                   │ │
  │ │                   '/opt/homebrew/Cellar/animdl/1.7.15/libexec/lib/pytho… │ │
  │ │ repository_name = 'animdl'                                               │ │
  │ │    version_file = 'animdl/core/__version__.py'                           │ │
  │ ╰──────────────────────────────────────────────────────────────────────────╯ │
  ╰──────────────────────────────────────────────────────────────────────────────╯
  AttributeError: 'NoneType' object has no attribute 'group'
```

</details>

full build log, https://github.com/Homebrew/homebrew-core/actions/runs/5255516838/jobs/9495700189
relates to Homebrew/homebrew-core#133515

**Comment by puffertron** [comment]
I am getting the same issue on my version of animdl (Installed with pip)


```
[puffertron@fedora ~]$ animdl
The project is operational. Use --help flag for help & be sure read the documentation!
                                                           justfoolingaround/animdl v1.7.15
Welcome, buddy.
   It is 02:45 PM on a beautiful Tuesday!
╭─────────────────────────────── Traceback (most recent call last) ────────────────────────────────╮
│ /home/puffertron/.local/bin/animdl:8 in <module>                                                 │
│                                                                                                  │
│   5 from animdl.__main__ import __animdl_cli__                                                   │
│   6 if __name__ == '__main__':                                                                   │
│   7 │   sys.argv[0] = re.sub(r'(-script\.pyw|\.exe)?$', '', sys.argv[0])                         │
│ ❱ 8 │   sys.exit(__animdl_cli__())                                                               │
│   9                                                                                              │
│                                                                                                  │
│ ╭──────────────────────────── locals ─────────────────────────────╮                              │
│ │  re = <module 're' from '/usr/lib64/python3.11/re/__init__.py'> │                              │
│ │ sys = <module 'sys' (built-in)>                                 │                              │
│ ╰─────────────────────────────────────────────────────────────────╯                              │
│                                                                                                  │
│ /home/puffertron/.local/lib/python3.11/site-packages/click/core.py:1130 in __call__              │
│                                                                                                  │
│ /home/puffertron/.local/lib/python3.11/site-packages/click/core.py:1055 in main                  │
│                                                                                                  │
│ /home/puffertron/.local/lib/python3.11/site-packages/click/core.py:1635 in invoke                │
│                                                                                                  │
│ /home/puffertron/.local/lib/python3.11/site-packages/click/core.py:1404 in invoke                │
│                                                                                                  │
│ /home/puffertron/.local/lib/python3.11/site-packages/click/core.py:760 in invoke                 │
│                                                                                                  │
│ /home/puffertron/.local/lib/python3.11/site-packages/click/decorators.py:26 in new_func          │
│                                                                                                  │
│ /home/puffertron/.local/lib/python3.11/site-packages/animdl/__main__.py:80 in __animdl_cli__     │
│                                                                                                  │
│    77 │   │   │   │   client.get(                                                                │
│    78 │   │   │   │   │   f"https://raw.githubusercontent.com/{author}/{repository_name}/{bran   │
│    79 │   │   │   │   ).text,                                                                    │
│ ❱  80 │   │   │   ).group(1)                                                                     │
│    81 │   │   │                                                                                  │
│    82 │   │   │   tuplisied_upstream, tuplised_current_version = tuple(                          │
│    83 │   │   │   │   map(int, upstream_version.split("."))                                      │
│                                                                                                  │
│ ╭─────────────────────────────────────────── locals ───────────────────────────────────────────╮ │
│ │          author = 'justfoolingaround'                                                        │ │
│ │          branch = 'master'                                                                   │ │
│ │          client = <httpx.Client object at 0x7f34585b1490>                                    │ │
│ │         console = <console width=150 ColorSystem.TRUECOLOR>                                  │ │
│ │       constants = <module 'animdl.core.cli.helpers.constants' from                           │ │
│ │                   '/home/puffertron/.local/lib/python3.11/site-packages/animdl/core/cli/hel… │ │
│ │             ctx = <click.core.Context object at 0x7f345ab9cad0>                              │ │
│ │  disable_update = False                                                                      │ │
│ │        greeting = 'It is 02:45 PM on a [bold red]beautiful[/] Tuesday!'                      │ │
│ │        regexlib = <module 'regex' from                                                       │ │
│ │                   '/usr/lib64/python3.11/site-packages/regex/__init__.py'>                   │ │
│ │ repository_name = 'animdl'                                                                   │ │
│ │    version_file = 'animdl/core/__version__.py'                                               │ │
│ ╰──────────────────────────────────────────────────────────────────────────────────────────────╯ │
╰──────────────────────────────────────────────────────────────────────────────────────────────────╯
AttributeError: 'NoneType' object has no attribute 'group'

```

It just started happening today, as far as I know. I have tried uninstalling and reinstalling the script.

**Comment by hunkyburrito** [comment]
I'm not sure if it will work with the building, but if you're just trying to use animdl then for now you can pass the `-x` flag until the version checking gets fixed.

**Comment by puffertron** [comment]
Thanks! Using -x works for me.

**Comment by chenrui333** [comment]
I can confirm it works with 1.7.16 release now.
